// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utugwkihiolthgqqzqeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dWd3a2loaW9sdGhncXF6cWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjIzNDgsImV4cCI6MjA2ODgzODM0OH0.UgVBwiWXcR7JEhDqgCz79tM7g3mLShs55XmYnX7qcD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});